### ISSUE TITLE
Open Window Settings binding not working

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#73]
When bound to a button, Open Window Settings never triggers.

**Steps to reproduce the behavior:**
Bind Open Window Settings to a button (I used right thumbstick click)

**Expected behavior:**
Binded button opens the window settings panel.

**Output Log:**
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4806499/output_log.txt)

**Additional Information:**

**Comment by Swingly6061** [comment]
Forgot to mention, this was on an Index.

**Comment by Xiexe** [comment]
This along with the left, right, and middle click non modifier bindings will be fixed in the next patch!

**Comment by Xiexe** [comment]
Should be fixed on beta branch! Will close issue if no further problems arise!

**Comment by Swingly6061** [comment]
Just tested this again, still not working apparently.
Unsure if it's SteamVR Input being dumb any more but XSOverlay does block game input of the thumbstick click while the button is bound, as it's supposed to when a binding works.

**Comment by Xiexe** [comment]
Okay, sorry about that, I missed something that was causing it to not function properly. This will be fixed in the next beta patch!
